name: opti_frontend
description: A Flutter camera-based frontend for Opti backend.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  camera: ^0.10.5+9
  http: ^1.1.0
  permission_handler: ^11.1.0
  open_filex: ^4.4.0
  cupertino_icons: ^1.0.6
  image: ^4.1.3
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/OPTIFOCUS_LOGO.png
    - assets/images/FOOTER.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/app_icon_bg.png"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"
